/**
 * Saadat — Data generator
 * Fetches surah metadata + Latin transliteration from alquran.cloud,
 * merges hand-curated Azerbaijani names, parses verse timings (Dawsari),
 * and generates the full recitation catalog (Dawsari + Al-Dakhin).
 *
 * Run: node scripts/fetch-data.mjs
 */
import { writeFileSync, mkdirSync, readFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const GEN = join(ROOT, "data", "generated");
mkdirSync(GEN, { recursive: true });

const log = (m) => console.log(`[fetch-data] ${m}`);

/** Azerbaijani names (hand-curated, all 114) */
const AZ = {
  1: "Fatihə", 2: "Bəqərə", 3: "Ali-İmran", 4: "Nisa", 5: "Maidə", 6: "Ənam",
  7: "Əraf", 8: "Ənfal", 9: "Tövbə", 10: "Yunus", 11: "Hud", 12: "Yusif",
  13: "Rəd", 14: "İbrahim", 15: "Hicr", 16: "Nəhl", 17: "İsra", 18: "Kəhf",
  19: "Məryəm", 20: "Taha", 21: "Ənbiya", 22: "Həcc", 23: "Möminun", 24: "Nur",
  25: "Furqan", 26: "Şüəra", 27: "Nəml", 28: "Qəsəs", 29: "Ənkəbut", 30: "Rum",
  31: "Loğman", 32: "Səcdə", 33: "Əhzab", 34: "Səba", 35: "Fatir", 36: "Yasin",
  37: "Saffat", 38: "Sad", 39: "Zümər", 40: "Qafir", 41: "Fussilət", 42: "Şura",
  43: "Zuxruf", 44: "Duxan", 45: "Casiyə", 46: "Əhqaf", 47: "Muhəmməd", 48: "Fəth",
  49: "Hucurat", 50: "Qaf", 51: "Zariyat", 52: "Tur", 53: "Nəcm", 54: "Qəmər",
  55: "Rəhman", 56: "Vaqiə", 57: "Hədid", 58: "Mücadilə", 59: "Həşr", 60: "Mümtəhinə",
  61: "Səff", 62: "Cümə", 63: "Münafiqun", 64: "Təğabun", 65: "Talaq", 66: "Təhrim",
  67: "Mülk", 68: "Qələm", 69: "Haqqə", 70: "Məaric", 71: "Nuh", 72: "Cinn",
  73: "Muzzəmmil", 74: "Muddəssir", 75: "Qiyamə", 76: "İnsan", 77: "Mürsəlat", 78: "Nəbə",
  79: "Naziat", 80: "Abəsə", 81: "Təkvir", 82: "İnfitar", 83: "Mutəffifin", 84: "İnşiqaq",
  85: "Buruc", 86: "Tariq", 87: "Əla", 88: "Ğaşiyə", 89: "Fəcr", 90: "Bələd",
  91: "Şəms", 92: "Leyl", 93: "Züha", 94: "İnşirah", 95: "Tin", 96: "Ələq",
  97: "Qədr", 98: "Bəyyinə", 99: "Zilzal", 100: "Adiyat", 101: "Qariə", 102: "Təkasür",
  103: "Əsr", 104: "Hüməzə", 105: "Fil", 106: "Qureyş", 107: "Maun", 108: "Kövsər",
  109: "Kafirun", 110: "Nəsr", 111: "Məsəd", 112: "İxlas", 113: "Fələq", 114: "Nas",
};

/** Accurate transliterated names (diacritic standard) — hand-curated */
const TRANS = {
  1: "Al-Fātiḥah", 2: "Al-Baqarah", 3: "Āli ʿImrān", 4: "An-Nisāʾ", 5: "Al-Māʾidah",
  6: "Al-Anʿām", 7: "Al-Aʿrāf", 8: "Al-Anfāl", 9: "At-Tawbah", 10: "Yūnus",
  11: "Hūd", 12: "Yūsuf", 13: "Ar-Raʿd", 14: "Ibrāhīm", 15: "Al-Ḥijr",
  16: "An-Naḥl", 17: "Al-Isrāʾ", 18: "Al-Kahf", 19: "Maryam", 20: "Ṭā Hā",
  21: "Al-Anbiyāʾ", 22: "Al-Ḥajj", 23: "Al-Muʾminūn", 24: "An-Nūr", 25: "Al-Furqān",
  26: "Ash-Shuʿarāʾ", 27: "An-Naml", 28: "Al-Qaṣaṣ", 29: "Al-ʿAnkabūt", 30: "Ar-Rūm",
  31: "Luqmān", 32: "As-Sajdah", 33: "Al-Aḥzāb", 34: "Sabaʾ", 35: "Fāṭir",
  36: "Yā Sīn", 37: "Aṣ-Ṣāffāt", 38: "Ṣād", 39: "Az-Zumar", 40: "Ghāfir",
  41: "Fuṣṣilat", 42: "Ash-Shūrā", 43: "Az-Zukhruf", 44: "Ad-Dukhān", 45: "Al-Jāthiyah",
  46: "Al-Aḥqāf", 47: "Muḥammad", 48: "Al-Fatḥ", 49: "Al-Ḥujurāt", 50: "Qāf",
  51: "Adh-Dhāriyāt", 52: "Aṭ-Ṭūr", 53: "An-Najm", 54: "Al-Qamar", 55: "Ar-Raḥmān",
  56: "Al-Wāqiʿah", 57: "Al-Ḥadīd", 58: "Al-Mujādilah", 59: "Al-Ḥashr", 60: "Al-Mumtaḥanah",
  61: "Aṣ-Ṣaff", 62: "Al-Jumuʿah", 63: "Al-Munāfiqūn", 64: "At-Taghābun", 65: "Aṭ-Ṭalāq",
  66: "At-Taḥrīm", 67: "Al-Mulk", 68: "Al-Qalam", 69: "Al-Ḥāqqah", 70: "Al-Maʿārij",
  71: "Nūḥ", 72: "Al-Jinn", 73: "Al-Muzzammil", 74: "Al-Muddaththir", 75: "Al-Qiyāmah",
  76: "Al-Insān", 77: "Al-Mursalāt", 78: "An-Nabaʾ", 79: "An-Nāziʿāt", 80: "ʿAbasa",
  81: "At-Takwīr", 82: "Al-Infiṭār", 83: "Al-Muṭaffifīn", 84: "Al-Inshiqāq", 85: "Al-Burūj",
  86: "Aṭ-Ṭāriq", 87: "Al-Aʿlā", 88: "Al-Ghāshiyah", 89: "Al-Fajr", 90: "Al-Balad",
  91: "Ash-Shams", 92: "Al-Layl", 93: "Aḍ-Ḍuḥā", 94: "Ash-Sharḥ", 95: "At-Tīn",
  96: "Al-ʿAlaq", 97: "Al-Qadr", 98: "Al-Bayyinah", 99: "Az-Zalzalah", 100: "Al-ʿĀdiyāt",
  101: "Al-Qāriʿah", 102: "At-Takāthur", 103: "Al-ʿAṣr", 104: "Al-Humazah", 105: "Al-Fīl",
  106: "Quraysh", 107: "Al-Māʿūn", 108: "Al-Kawthar", 109: "Al-Kāfirūn", 110: "An-Naṣr",
  111: "Al-Masad", 112: "Al-Ikhlāṣ", 113: "Al-Falaq", 114: "An-Nās",
};

async function fetchJson(url) {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`${url} → HTTP ${res.status}`);
  return res.json();
}

const writeTs = (name, value) =>
  writeFileSync(join(GEN, `${name}.ts`), `// Generated by scripts/fetch-data.mjs — do not edit by hand.\nexport default ${JSON.stringify(value)} as const;\n`);

/* 1 ── Surah metadata (alquran.cloud) */
log("Fetching surah metadata…");
const surahMeta = await fetchJson("https://api.alquran.cloud/v1/surah");
const surahs = surahMeta.data.map((s) => ({
  id: s.number,
  number: s.number,
  arabicName: s.name,
  englishName: s.englishName,
  transliteratedName: TRANS[s.number] ?? s.englishName,
  azerbaijaniName: AZ[s.number] ?? s.englishName,
  meaning: s.englishNameTranslation,
  verses: s.numberOfAyahs,
  revelationType: s.revelationType,
}));
writeTs("surahs", surahs);
log(`Surahs: ${surahs.length}`);

/* 2 ── Latin transliteration (alquran.cloud en.transliteration) */
log("Fetching transliteration (6236 verses)…");
const transRes = await fetchJson("https://api.alquran.cloud/v1/quran/en.transliteration");
const perSurah = {};
for (const s of transRes.data.surahs) {
  const key = String(s.number);
  perSurah[key] = s.ayahs.map((a) => (a.text ?? "").replace(/^\uFEFF/, ""));
}
writeFileSync(
  join(ROOT, "public", "data", "transliterations.json"),
  JSON.stringify(perSurah)
);
log(`Transliteration: ${Object.keys(perSurah).length} surahs covered`);

/* 2b ── Arabic (Uthmani, alquran.cloud quran-uthmani) */
log("Fetching Arabic Uthmani (6236 verses)…");
try {
  const arabicRes = await fetchJson("https://api.alquran.cloud/v1/quran/quran-uthmani");
  const perSurahAr = {};
  for (const s of arabicRes.data.surahs) {
    const key = String(s.number);
    perSurahAr[key] = s.ayahs.map((a) => (a.text ?? "").replace(/^\uFEFF/, ""));
  }
  writeFileSync(
    join(ROOT, "public", "data", "arabic.json"),
    JSON.stringify(perSurahAr)
  );
  log(`Arabic: ${Object.keys(perSurahAr).length} surahs covered`);
} catch (e) {
  log(`Arabic fetch failed: ${e.message} — writing fallback if missing`);
  const arabicPath = join(ROOT, "public", "data", "arabic.json");
  if (!existsSync(arabicPath)) {
    // Fallback: empty per-surah structure so the build still succeeds
    // (real data will be fetched on next successful run).
    const fallback = {};
    for (const s of surahs) fallback[String(s.number)] = [];
    // Try to populate with a minimal placeholder for surah 1 so UI isn't blank
    fallback["1"] = [
      "بِسْمِ ٱللَّهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ",
      "ٱلْحَمْدُ لِلَّهِ رَبِّ ٱلْعَٰلَمِينَ",
      "ٱلرَّحْمَٰنِ ٱلرَّحِيمِ",
      "مَٰلِكِ يَوْمِ ٱلدِّينِ",
      "إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ",
      "ٱهْدِنَا ٱلصِّرَٰطَ ٱلْمُسْتَقِيمَ",
      "صِرَٰطَ ٱلَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ ٱلْمَغْضُوبِ عَلَيْهِمْ وَلَا ٱلضَّآلِّينَ",
    ];
    writeFileSync(arabicPath, JSON.stringify(fallback));
    log("Arabic fallback written (surah 1 placeholder + empty others)");
  } else {
    log("Arabic fallback already exists — keeping it");
  }
}

/* 3 ── Verse timings (Dawsari, everyayah / VerseByVerseQuran.com) */
log("Parsing verse timings…");
const timingsDir = process.env.TIMINGS_DIR ?? join(ROOT, "..", "AppData", "Local", "Temp", "opencode", "timings", "extracted");
const timings = {};
if (existsSync(timingsDir)) {
  for (let n = 1; n <= 114; n++) {
    const f = join(timingsDir, String(n).padStart(3, "0") + ".txt");
    if (!existsSync(f)) continue;
    timings[String(n)] = readFileSync(f, "utf8").trim().split(/\r?\n/).map((v) => Number(v));
    // The last entry is the surah-end timestamp (N+1 for most surahs) — strip it
    // so the array length always equals the verse count.
    if (timings[String(n)].length > surahs.find((s) => s.number === n)?.verses) {
      timings[String(n)].pop();
    }
  }
}
writeTs("timings", timings);
log(`Timings: ${Object.keys(timings).length} surahs`);

/* 4 ── Recitation catalog */
log("Generating recitation catalog…");
const dawsariDurations = {};
for (const [n, arr] of Object.entries(timings)) {
  dawsariDurations[n] = Math.round((arr[arr.length - 1] + 7000) / 1000); // tail ≈ 7s
}
const recitations = [];
for (const s of surahs) {
  const n = String(s.number).padStart(3, "0");
  recitations.push({
    id: `dawsari-${n}`,
    reciterId: "yasir-al-dawsari",
    surahId: s.number,
    audioUrl: `https://cdn.islamic.network/quran/audio-surah/128/ar.yasseraldossari/${s.number}.mp3`,
    durationSeconds: dawsariDurations[String(s.number)] ?? null,
    source: "Islamic Network CDN (quranicaudio.com archive)",
  });
  recitations.push({
    id: `aldakhin-${n}`,
    reciterId: "haitham-al-dakhin",
    surahId: s.number,
    audioUrl: `https://server16.mp3quran.net/h_dukhain/Rewayat-Hafs-A-n-Assem/${n}.mp3`,
    durationSeconds: null,
    source: "mp3quran.net — official hosted mushaf",
  });
}
writeTs("recitations", recitations);
log(`Recitations: ${recitations.length} (2 reciters × 114 surahs)`);

log("Done ✅");
